name: 打包
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        default: 'latest'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载源代码
        uses: actions/checkout@v4
      - name: 设置 Node.js 版本
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: ok
        run: echo "ok"


